# -*- coding: utf-8 -*-
"""上市上櫃股票清單.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNAZDCSMI-G7xGHtI1ONcD5pxuntIhUG

原文網址：[如何用Python獲得上市上櫃股票清單?](https://www.finlab.tw/python%EF%BC%9A%E5%A6%82%E4%BD%95%E7%8D%B2%E5%BE%97%E4%B8%8A%E5%B8%82%E4%B8%8A%E6%AB%83%E8%82%A1%E7%A5%A8%E6%B8%85%E5%96%AE/)
"""

import requests
from io import StringIO
import pandas as pd
import datetime
import os

path = 'D:/GitHub/TwStock/'

# 爬取全台灣上市上櫃公司
res1 = requests.get("https://isin.twse.com.tw/isin/C_public.jsp?strMode=2")
res2 = requests.get("https://isin.twse.com.tw/isin/C_public.jsp?strMode=4")
# 將網頁表格儲存成DataFrame
df1 = pd.read_html(StringIO(res1.text))[0]
df2 = pd.read_html(StringIO(res2.text))[0]

# 設定column名稱，留下第三行以後的資料
df1.columns = df1.iloc[0]
df1 = df1.iloc[2:]
df2.columns = df2.iloc[0]
df2 = df2.iloc[2:]

# 先移除row，再移除column，超過三個NaN則移除
df1 = df1.dropna(thresh=3, axis=0).dropna(thresh=3, axis=1)
df2 = df2.dropna(thresh=3, axis=0).dropna(thresh=3, axis=1)

# 設定過濾條件，並使用過濾條件過濾資料框
f = (df1['CFICode'] == 'ESVUFR')
df1 = df1[f]
f = (df2['CFICode'] == 'ESVUFR')
df2 = df2[f]

# 獲得今日日期並轉換成YYYYmmdd格式
date = datetime.date.today()
date = str(date).replace('-','')
# 將原始網頁表格儲存成csv檔
stock_names = pd.concat([df1, df2]).sort_values('有價證券代號及名稱')
stock_names.to_csv(path + 'rawdata'  + date + '.csv')

# 將表格內「有價證券代號及名稱」拆成「證券代號」及「證券名稱」
split = stock_names['有價證券代號及名稱'].str.split('　', expand=True)
stock_names['證券代號'] = split[0]
stock_names['證券名稱'] = split[1]

# 刪除資料框的前兩列，只留下需要的五個欄位
stock_names = stock_names.iloc[:, 2:]
stock_names = stock_names[['證券代號', '證券名稱', '上市日', '市場別', '產業別']]

# 原始資料裡，只有4148與公司名中間有空格，故單獨處理。
# 找到證券代號為 "4148 全宇生技-KY" 的列索引，
# 將選取到的列索引轉換為列表，並取第一個元素。
index = stock_names[stock_names['證券代號'] == '4148 全宇生技-KY'].index.tolist()[0]

# 將原本'4148 全宇生技-KY'的第二個字串放到證券名稱，
# 第一個字串放到證券代號。
stock_names['證券名稱'][index] = stock_names['證券代號'][index].split()[1]
stock_names['證券代號'][index] = stock_names['證券代號'][index].split()[0]
stock_names = stock_names.set_index('證券代號')

# 讀取檔案目錄
all_file_name = os.listdir(path)

# 尋找檔案名稱包含"stock_names"的檔案
for filename in all_file_name:
  if "stock_names" in filename:
    file_path = path + filename


today_filename = 'stock_names' + date + '.csv'
stock_names.to_csv(path + today_filename)
print(date + '已取得最新的上市上櫃公司')

#待修改
try:
  if not filename == today_filename:
    if os.path.exists(file_path):
      # 刪除舊檔案
      os.remove(file_path)
      print("刪除舊資料")
except:
  pass

'''
print(today_filename)
print(all_file_name)
print(filename)
'''
